name: declare
description: "A new Flutter project."
version: 0.0.1
repository: https://github.com/ArcaneArts/declare
environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  pylon: ^2.0.4+1
  linked_scroll_controller: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter: