name: declare
description: "A new Flutter project."
version: 0.0.1
repository: https://github.com/ArcaneArts/declare
environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  shadcn_flutter: ^0.0.19
  gusto_neumorphic: ^3.3.0
  toxic: ^1.3.1
  toxic_flutter: ^1.0.2+1
  gap: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter: